### ISSUE TITLE
Ошибка при клонировании

### ISSUE THREAD

**Issue by pelageech** [dariakhaetskaya/NSU-CS-Helper#1]
Привет, у тебя в ./Magic Logic есть файл, на конце которого есть вопросительный знак
Так вот, в винде нельзя использовать вопросительные, поэтому такая ошибка
```error: invalid path 'Math Logic/Есть ли жизнь после ТОСМа?.pdf```
Поправь пж, а я залью новый раздел)

**Comment by dariakhaetskaya** [comment]
Проверяй

**Comment by pelageech** [comment]
Гуд!
